add lab 5
igorv404/airline-iot pull request #1
Opened 2022-04-22 10:29 UTC by igorv404

2022-04-26 22:26 UTC, ChumakAn requested changes

2022-04-26 22:26 UTC, ChumakAn commented on airline/src/test/java/ua/lviv/iot/airline/managers/impl/AirlineWriterTest.java
> +  void writeCSV() {
write test for this part of code too, assuming you get the empty file, do not have file and have the correct one

2022-04-27 08:20 UTC, igorv404 commented on airline/src/test/java/ua/lviv/iot/airline/managers/impl/AirlineManagerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
done

2022-04-27 08:21 UTC, igorv404 commented on airline/src/test/java/ua/lviv/iot/airline/managers/impl/AirlineWriterTest.java
> +  void writeCSV() {
already done

2022-04-28 16:26 UTC, merged